dap = require("dap")
dapui = require("dapui")
dapui.setup()

vim.keymap.set('n', '<F8>', function() dap.continue() end)
vim.keymap.set('n', '<F10>', function() dap.step_over() end)
vim.keymap.set('n', '<F11>', function() dap.step_into() end)
vim.keymap.set('n', '<F12>', function() dap.step_out() end)
vim.keymap.set('n', '<Leader>dB', function() dap.toggle_breakpoint() end)
vim.keymap.set('n', '<Leader>dbl', function() dap.set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end)
vim.keymap.set('n', '<Leader>dr', function() dap.repl.open() end)
vim.keymap.set('n', '<Leader>dL', function() dap.run_last() end)
vim.keymap.set('n', '<Leader>dut', function() dapui.toggle() end)
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
  require('dap.ui.widgets').hover()
end)
